### ISSUE TITLE
parameter_estimation.py min_snps 

### ISSUE THREAD

**Issue by Arosengren** [ZhiGroup/RaPID#13]
Hello I'm trying to run the parameter estimation. It only seems to run if all 6 args are supplied and not only using 4 as per the usage instructions. (Usage: python parameter_estimation <vcf_input_file> <error_rate> <num_haplotypes> <min_snps>, or\\ python parameter_estimation <vcf_input_file> <error_rate> <num_haplotypes> <min_snps> <num_run> <num_success>")

However my real question is in regard to the 4th args "min_snps". My thought would be that this would be the minimum of SNPS in a IBD segment of a given length. It is not clear for me how to calculate this. It would at first appear as a rather simple arithmetic exercise. However this doesn't seem to be the case when looking at the number from the supplementary table2, and presumable is due to the requirement of 90% of IBD segments to be longer? 

Could you advise how to calculate this min_snps given chromosomal length in MB and cM and number of included SNPs.
Clarify whether this number should or shouldn't be calculated per chromosome basis or across all chr included in analysis i.e autosomes. 

In addition running the parameter estimation using 3 different min_snps (10,100,800) (all other args identical) all gave the same output "50 300"

I appreciate your help.

**Comment by ardalan-n** [comment]
Hi,

The minimum number of SNPs is simply the number of sites covering IBD segments greater than a given length in cM. You can make a simple assumption that the genetic distance is evenly distributed (so the markers) and divide the total number of available sites by the total genetic length and multiply with the minimum length in cM. Since some of the IBDs (in some regions) may contain fewer sites, then it may be useful to consider a small tolerance (10%). A more accurate solution is to compute the minimum number of sites across the chromosome to cover _L_ cM and pick the 10th percentile. 

Having said that, the computation should not be too sensitive to small changes in the number of sites. So, even the simple formula  _α\*L\*#sites/T_  (_α_ = 0.9, _T_ : total genetic length) should probably work. You can also pick a small chromosome (e.g. chromosome 20) and estimate the parameter(s) which should hold for other autosomal chromosomes, assuming all chromosome belong to same panel. 

Best,
Ardalan

**Comment by Arosengren** [comment]
Thank you the reply, it explains it nicely and as expected.

Doing the simple calculation here for my chr21 data, would suggest a min_snp ~700-800 (0.9*5cM*11606/~62cM) 
For ~100k haplotypes and error rate of 0.0025,10 runs and two successes the suggested window range from the script seems to be 50 300, which seems quite far from the 2-6 suggested for the UKBB chr22 having a comparable no of sites (10911), values from S2.  (I've only included SNPS with maf > 0.05) 
 
I will go through my setup again.

**Comment by ardalan-n** [comment]
Actually, I noticed the minimum number of SNPs was set to 12000 after the first initialization. Please comment out the following line and re-run the script.
min_length_SNPs = 12000#14000
I will fix it now too.

Best,
Ardalan
