### ISSUE TITLE
FATAL ERROR: failed to get M

### ISSUE THREAD

**Issue by XLZH** [ZhiGroup/RaPID#4]
I have built the genotype file(.vcf) and genetic map file(.map) and run the command bellow:
`RaPID_v.1.6 -i xlzh.vcf -o xlzh -r 10 -w 0.02 -s 2 -l 3.0 -g xlzh.map`

But output with an fatal error:
`FATAL ERROR: failed to get M`
So could you please tell me what's that mean? Looking forward for your reply, thanks

**Comment by ardalan-n** [comment]
Hi,

It seems that there's something wrong with the intermediate files that are being generated. The VCF file should be in **.gz compressed format**. Please compress the input file using _gzip_ and re-run the program. If the problem is still not resolved, could you please look at the output folder (xlzh) and report the first line of one of the created files? The first line only contains the number of individuals (haplotypes) and the chromosome length. 

Thanks,
Ardalan

**Comment by XLZH** [comment]
Thanks for your reply! The problem was solved by compressed my input file into .gz format. Thanks very much!
